#import "@preview/curryst:0.6.0": *

#let hypos = grid.with(columns: 6, gutter: 10pt)

#let th(hypo) = rule.with(name: [_ #hypo _])
#let impl-i(hypo) = rule.with(name: [$-> I$ _ #hypo _])
#let impl-e = rule.with(name: $-> E$)
#let and-i = rule.with(name: $and I$)
#let and-el = rule.with(name: $and E_l$)
#let and-er = rule.with(name: $and E_r$)
#let or-e(hypo) = rule.with(name: [$or E$ _ #hypo _])
#let or-il = rule.with(name: $or I_l$)
#let or-ir = rule.with(name: $or I_r$)
#let not-i(hypo) = rule.with(name: [$not I$ _ #hypo _])
#let not-e = rule.with(name: $not E$)
#let raa(hypo) = rule.with(name: [_RAA #hypo _])
#let truth-i = rule.with(name: $top I$)
#let false-e = rule.with(name: $bot E$)
#let bi-i(hypo) = rule.with(name: [$<-> I$ _ #hypo _])
#let bi-el = rule.with(name: $<-> E_l$)
#let bi-er = rule.with(name: $<-> E_r$)
#let forall-i = rule.with(name: $forall I$)
#let forall-e = rule.with(name: $forall E$)
#let exists-i = rule.with(name: $exists I$)
#let exists-e(hypo) = rule.with(name: [$exists E$ _ #hypo _])
#let refl = rule.with(name: [refl])
#let symm = rule.with(name: [symm])
#let trans = rule.with(name: [trans])
#let subst-1 = rule.with(name: [subst(1)])
#let subst-2 = rule.with(name: [subst(2)])

